using System;
using Melia.Shared.Game.Const;
using Melia.Zone.World.Actors;

namespace Melia.Zone.Skills.Handlers.Clerics.Zealot
{
	/// <summary>
	/// Fervor, the Zealot class resource.
	/// Per the concept (Zealot_Rework_Konzept.xlsx v1.0) it is generated by
	/// Brand the Heretic — on a marked kill, or on the empowered hit against
	/// bosses — and spent by Temper the Flame and Blind Faith. Kept in one
	/// place so every skill agrees on how stacks are counted and consumed.
	/// </summary>
	/// <remarks>
	/// Rides on the unused BrambleRage buff ("Lunacy", renamed client-side),
	/// which is already permanent and, via buffs_overrides, capped at 20
	/// stacks, showing a stack count on the buff icon.
	/// </remarks>
	public static class ZealotFervor
	{
		/// <summary>
		/// The buff carrying the stacks.
		/// </summary>
		public const BuffId FervorBuff = BuffId.BrambleRage;

		/// <summary>
		/// Matches overBuff in the buff db entry.
		/// </summary>
		public const int MaxStacks = 20;

		/// <summary>
		/// Returns how many stacks the entity currently holds, 0 if none.
		/// </summary>
		public static int GetStacks(ICombatEntity entity)
		{
			if (!entity.TryGetBuff(FervorBuff, out var buff))
				return 0;

			// An active buff is worth at least one stack, regardless of where
			// the overbuff counter starts.
			return Math.Max(1, Math.Min(MaxStacks, buff.OverbuffCounter));
		}

		/// <summary>
		/// Adds the given number of stacks, starting the buff if it is not
		/// running yet. Only notifies the client when the visible count
		/// actually changes — every buff update makes the client play its
		/// refresh feedback.
		/// </summary>
		public static void AddStacks(ICombatEntity entity, int amount, SkillId skillId)
		{
			if (amount <= 0)
				return;

			if (entity.TryGetBuff(FervorBuff, out var buff))
			{
				var before = GetStacks(entity);
				if (before >= MaxStacks)
					return;

				buff.OverbuffCounter = Math.Min(MaxStacks, before + amount);
				buff.NotifyUpdate();
				return;
			}

			// The db entry has duration 0, so the buff persists until spent.
			entity.StartBuff(FervorBuff, 1, 0f, TimeSpan.Zero, entity, skillId);

			if (entity.TryGetBuff(FervorBuff, out var started))
			{
				started.OverbuffCounter = Math.Min(MaxStacks, amount);
				started.NotifyUpdate();
			}
		}

		/// <summary>
		/// Spends the given number of stacks; the buff ends when the pool is
		/// empty. Returns how many were actually consumed.
		/// </summary>
		public static int Consume(ICombatEntity entity, int amount)
		{
			var stacks = GetStacks(entity);
			if (stacks <= 0 || amount <= 0)
				return 0;

			var consumed = Math.Min(stacks, amount);
			var remaining = stacks - consumed;

			if (remaining <= 0)
			{
				entity.StopBuff(FervorBuff);
			}
			else if (entity.TryGetBuff(FervorBuff, out var buff))
			{
				buff.OverbuffCounter = remaining;
				buff.NotifyUpdate();
			}

			return consumed;
		}

		/// <summary>
		/// Spends every stack and returns how many there were, so a skill can
		/// scale itself by what it just consumed.
		/// </summary>
		public static int ConsumeAll(ICombatEntity entity)
		{
			var stacks = GetStacks(entity);

			if (stacks > 0)
				entity.StopBuff(FervorBuff);

			return stacks;
		}
	}
}
